import { CameraSchema, type Camera } from "./schemas";
import { camerasData } from "./_data_cameras";

/**
 * Camera data is embedded as a TS module (generated by the build script
 * from data/cameras.json) so Workers can import it at runtime without any
 * filesystem access — Workers don't have `node:fs`.
 *
 * Re-run `bun run scrape && bun run build` to refresh the embedded snapshot.
 */

// Validate at module load — a bad scrape can't break runtime.
export const CAMERAS: Camera[] = camerasData.map((c) => CameraSchema.parse(c));

export function getCameras(): Camera[] {
  return CAMERAS;
}
