import { rm, cp, readFile, writeFile } from "node:fs/promises";

// Clean previous build
await rm("./dist", { recursive: true, force: true });

// Inline cameras.json into the bundle so Workers can read it at runtime.
// We embed it as a JS module under src/_data_cameras.ts so the relative
// path resolution in src/api.ts (../data/cameras.json) works both during
// dev (real fs) and at runtime (bundled).
const camerasJson = JSON.parse(await readFile("./data/cameras.json", "utf-8"));
const generatedModule =
  "// AUTO-GENERATED by build script — do not edit.\n" +
  "export const camerasData = " +
  JSON.stringify(camerasJson.cameras ?? []) +
  ";\n";
await writeFile("./src/_data_cameras.ts", generatedModule);

// Bundle the client-side code (hydration glue — server already rendered SSR).
const buildResult = await Bun.build({
  entrypoints: ["./src/client.tsx"],
  outdir: "./dist",
  minify: true,
  target: "browser",
  naming: "client.[ext]",
});

if (!buildResult.success) {
  // oxlint-disable-next-line no-console
  for (const log of buildResult.logs) console.error(log);
  process.exit(1);
}

// Copy static assets into dist/. Pages Static Assets (configured in
// wrangler.toml [assets]) serves these directly without going through the
// Pages Function — keeping the function bundle small and fast.
await cp("./src/style.css", "./dist/style.css");

// oxlint-disable-next-line no-console
console.log("Build complete → ./dist/");
