import { rm, cp, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

// Clean previous build
await rm("./dist", { recursive: true, force: true });

// Inline cameras.json into the bundle so Workers can read it at runtime.
const camerasJson = JSON.parse(await readFile("./data/cameras.json", "utf-8"));
const generatedCameras =
  "// AUTO-GENERATED by build script — do not edit.\n" +
  "export const camerasData = " +
  JSON.stringify(camerasJson.cameras ?? []) +
  ";\n";
await writeFile("./src/_data_cameras.ts", generatedCameras);

// Inline cookies.json (if present) so the Worker has a valid session
// to proxy streams. The CCTV upstream blocks CF data-center IPs from
// receiving cookies via direct fetch, so we capture them via cloakbrowser
// at deploy time and bake them in. Shortest cookie TTL is ~1 hour —
// refresh by re-running `bun run scrape && bun run build && bun run deploy`.
let cookiesModule =
  "// AUTO-GENERATED. No cookies yet — run `bun run scrape` first.\n" +
  'export const bakedCookieHeader = "";\n';
if (existsSync("./data/cookies.json")) {
  const cookiesJson = JSON.parse(
    await readFile("./data/cookies.json", "utf-8"),
  );
  cookiesModule =
    "// AUTO-GENERATED by build script — do not edit.\n" +
    "// Scraped at: " +
    (cookiesJson.scrapedAt ?? "?") +
    "\n" +
    "// Expires at: " +
    (cookiesJson.expiresAt ?? "?") +
    "\n" +
    "export const bakedCookieHeader = " +
    JSON.stringify(cookiesJson.cookieHeader ?? "") +
    ";\n" +
    "export const bakedCookieExpiresAt = " +
    JSON.stringify(cookiesJson.expiresAt ?? null) +
    ";\n";
}
await writeFile("./src/_data_cookies.ts", cookiesModule);

// Bundle the client-side code (hydration glue — server already rendered SSR).
const buildResult = await Bun.build({
  entrypoints: ["./src/client.tsx"],
  outdir: "./dist",
  minify: true,
  target: "browser",
  naming: "client.[ext]",
});

if (!buildResult.success) {
  // oxlint-disable-next-line no-console
  for (const log of buildResult.logs) console.error(log);
  process.exit(1);
}

// Copy static assets into dist/. Pages Static Assets (configured in
// wrangler.toml [assets]) serves these directly without going through the
// Pages Function — keeping the function bundle small and fast.
await cp("./src/style.css", "./dist/style.css");

// oxlint-disable-next-line no-console
console.log("Build complete → ./dist/");
